name: Actions Workflows
on: push
env:
  WF_ENV: ${{ secrets.ENV_SECRET }}
  WK_ENV: Everything up to date

jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: echo "${WF_ENV}"
      - name: echo env II
        run: echo "${WK_ENV}"


