name: Actions Workflows
on: push
env:
  WF_ENV: ${{ secrets.ENV_SECRET }}
  WK_ENV: Everything up to date

jobs:

  random-file:
    runs-on: ubuntu-latest
    steps:
      - name: push a random-file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "kartikey.srivastava999@gmail.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add .
          git commit -m "Commit aa"
          git push
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        run: echo "${WF_ENV}"
      - name: echo env II
        run: echo "${WK_ENV}"



