name: Node Version

on: [push]

jobs:
  node-version:
    strategy:
      matrix:
        node-version: [6,7,8]  
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Log node-version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log new node-version
        run: node -v