name: Node Version

on: [push]

jobs:
  node-version:
    strategy:
      matrix:
        node-version: [6,7,8]  
        include:
          - node-version: 6
          - is_ubuntu_6: "true"
        exclude:
          - node-version: 8
      fail-fast: true
    runs-on: ubuntu-latest
    env: 
      IS_UBUNTU_6: ${{ matrix.is_ubuntu_6 }}
    steps:
      - name: Log node-version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log new node-version
        run: |
          node -v
          echo $IS_UBUNTU_6